### ISSUE TITLE
Fails to load on Cinnamon 5.4.3

### ISSUE THREAD

**Issue by DarNCelsius** [nathan818fr/cinnamon-back-to-monitor#1]
```
error t=2022-07-23T09:32:29Z 
[back-to-monitor@nathan818fr]: Meta.WindowTileType is undefined
[back-to-monitor@nathan818fr]: Error importing extension.js from back-to-monitor@nathan818fr
```

**Comment by nathan818fr** [comment]
Thank you for the report.

I have started to add support for Cinnamon 5.4 in this branch: [feature/cinnamon5.4](https://github.com/nathan818fr/cinnamon-back-to-monitor/tree/feature/cinnamon5.4).

The extension no longer causes errors and loads, but unfortunately it seems that there have been more changes to Cinnamon than expected.
When screens are updated Cinnamon now moves the windows itself before the extension can detect it. But he also seems to restore their position himself afterwards.

So it seems that Cinnamon 5.4 partially embeds the features of this extension.
Only the automatic minimization of moved windows is missing.

I am very busy right now and don't have time to investigate these new behaviors.
But I will look into it as soon as I can.

**Comment by nathan818fr** [comment]
Fixed by https://github.com/nathan818fr/cinnamon-back-to-monitor/commit/5983d5f866737bff7f74374b7af8bd4ed5c0d805

**Comment by nathan818fr** [comment]
Fixed by https://github.com/nathan818fr/cinnamon-back-to-monitor/commit/5983d5f866737bff7f74374b7af8bd4ed5c0d805
