### ISSUE TITLE
[ ISSUE ] Problem with Cinnamon 

### ISSUE THREAD

**Issue by heyvoon** [nathan818fr/cinnamon-back-to-monitor#2]
![image](https://user-images.githubusercontent.com/3281265/198300214-07d7aad7-4c7c-4c5b-bc4f-7008b6156f05.png)

![image](https://user-images.githubusercontent.com/3281265/198299621-2a83f66b-b86f-4b54-95ca-1b441845d05e.png)

**Comment by nathan818fr** [comment]
This extension is not yet compatible with Cinnamon 5.4:
https://github.com/nathan818fr/cinnamon-back-to-monitor/issues/1#issuecomment-1193213456
